# 请确保添加的 Secrets 名字为 ACTION_DEPLOY_KEY
# 65cab5a1c0b71e0db23ab2104e344b777178c8de
name: 自动部署 Hexo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: 开始运行
        uses: actions/checkout@v1

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 配置 Git 环境
        env:
          GITEE: ${{secrets.GITEE}}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITEE" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
          git config --global user.name "kevinroy"
          git config --global user.email "luoguangrong0312@gmail.com"

      - name: 安装 Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm i -g hexo-cli
          npm i

      - name: 安装插件
        run: |
          npm install

      - name: 部署博客
        run: |
          rm -rf .deploy_git
          hexo clean && hexo g && hexo douban -bm && gulp && hexo deploy
          rm ~/.ssh/id_rsa
